//
//  DataService.swift
//  FormulaOne
//
//  Created by Matthew Toal on 8/24/23.
//

import Foundation

struct DataService {
    
    func getData() -> [Team] {
        
        return [Team(name: "Red Bull Racing",
                     imageName: "redBullLogo",
                     drivers: [
                        Driver(name: "Sergio Perez",
                               summary: "Sergio Michel \"Checo\" Pérez Mendoza was born 26 January 1990 is a Mexican racing driver who races in Formula One for Red Bull Racing, having previously driven for Sauber, McLaren, Force India, and Racing Point. He has won six F1 Grand Prix races. He won his first Grand Prix driving for Racing Point at the 2020 Sakhir Grand Prix, breaking the record for the number of starts before a race win at 190.",
                               driverNumber: "11",
                               imageName: "sergioPerez",
                               longDescription: "Sergio earned his first Formula One pole position at the 2022 Saudi Arabian Grand Prix, breaking the record for the most races before a first pole position at 215. Up until 2012, Pérez was a member of the Ferrari Driver Academy. He made his Formula One debut driving for Sauber during the 2011 season. He took his first Formula One podium at the 2012 Malaysian Grand Prix with Sauber. Due to his young age and performance, he was referred to as \"The Mexican Wunderkind\". Pérez joined McLaren for the 2013 season, but the team did not score a single podium finish. Subsequently, the team decided to replace Pérez with Kevin Magnussen for the 2014 season. Force India signed Pérez for the 2014 season with a €15 million contract. He remained with Force India when the team went into administration in 2018 and reformed as the Racing Point team for 2019. In 2019, Racing Point signed a three-year extension with Pérez. In September 2020, Racing Point announced that Pérez would be leaving the team at the end of the season as Sebastian Vettel, a four-time F1 world champion, had been signed to replace him. In December, Pérez signed with Red Bull Racing for the 2021 season. He has a contract with Red Bull Racing until the end of the 2024 season."),
                        
                        Driver(name: "Max Verstappen",
                               summary: "Max Emilian Verstappen was born 30 September 1997 is a Dutch and Belgian racing driver and the 2021 and 2022 Formula One World Champion. He competes under the Dutch flag in Formula One with Red Bull Racing.",
                               driverNumber: "1",
                               imageName: "maxVerstappen",
                               longDescription: "Max is the son of racing drivers Jos Verstappen, who also competed in Formula One, and Sophie Kumpen. He had a successful run in junior karting and single-seater categories – including KF3, WSK World Series, KZ2 and European Formula 3 – beating several records. At the 2015 Australian Grand Prix, when he was aged 17 years, 166 days, he became the youngest driver to compete in Formula One. After spending the 2015 season with Scuderia Toro Rosso, Verstappen started his 2016 campaign with the Italian team before being promoted to parent team Red Bull Racing after four races as a replacement for Daniil Kvyat. At the age of 18, he won the 2016 Spanish Grand Prix on his debut for Red Bull Racing, becoming the youngest-ever driver and the first After winning the 2021 Abu Dhabi Grand Prix, Verstappen became the first Dutch driver to win the Formula One World Championship, and the 34th Formula One World Drivers' Champion. He won his second consecutive Formula One championship the next season. As of the 2023 Belgian Grand Prix, Verstappen has achieved 45 victories and 27 pole positions. He scored the first hat-trick of his career at the 2021 French Grand Prix and his first grand slam at the 2021 Austrian Grand Prix. He scored his second grand slam at the 2022 Emilia Romagna Grand Prix and his third at the 2023 Spanish Grand Prix. Verstappen is set to remain at Red Bull until at least the end of the 2028 season after signing a contract extension.")
                        ],
                    carImage: "redBullCar"),
                Team(name: "Mercedes", imageName: "mercedesLogo", drivers: [
                    Driver(name: "George Russell",
                           summary: "George William Russell was born 15 February 1998 is a British racing driver currently competing in Formula One for Mercedes. He previously raced for Williams from 2019 to 2021.",
                           driverNumber: "63",
                           imageName: "georgeRussell",
                           longDescription: "After winning several karting championships including the CIK-FIA European Karting Championship in 2012, he repeated his success by becoming the 2018 Formula 2 champion and the 2017 GP3 Series champion, driving for ART in both campaigns to become one of only three drivers to win both championships in his respective rookie seasons. Following his Formula 2 championship win, Russell signed for Williams in 2019, making his debut at the 2019 Australian Grand Prix, although he stood in for Lewis Hamilton at Mercedes at the 2020 Sakhir Grand Prix, but was denied of a Grand Prix victory due to strategical errors. In 2022, Russell departed Williams to race for the Mercedes team, having been a member of the Mercedes Junior Driver Programme since 2017. Russell achieved his first F1 victory at the 2022 São Paulo Grand Prix. As of the 2023 Belgian Grand Prix, Russell has achieved one victory, one pole position, six fastest laps and ten podium finishes in his career. Russell agreed to drive for Mercedes on a multi-year deal, without giving any detailed information about the contract length."),
                    Driver(name: "Lewis Hamilton",
                           summary: "Sir Lewis Carl Davidson Hamilton was born 7 January 1985) is a British racing driver currently competing in Formula One, driving for Mercedes. In Formula One, Hamilton has won a joint-record seven World Drivers' Championship titles (tied with Michael Schumacher), and holds the records for the most wins (103), pole positions (104), and podium finishes (195), among others.", driverNumber: "44",
                           imageName: "lewisHamilton",
                           longDescription: "Born and raised in Stevenage, Hertfordshire, Hamilton joined the McLaren young driver programme in 1998. This led to a Formula One drive with McLaren from 2007 to 2012, making Hamilton the first, and so far only, black driver to race in the series. In his inaugural season, Hamilton set numerous records as he finished runner-up to Kimi Räikkönen by one point. The following season, he won his maiden title in dramatic fashion—making a crucial overtake on the last lap of the last race of the season—to become the then-youngest ever Formula One World Champion. After six years with McLaren, Hamilton signed with Mercedes in 2013. Changes to the regulations for 2014 mandating the use of turbo-hybrid engines saw the start of a highly successful period for Hamilton, during which he won six further drivers' titles. Consecutive titles came in 2014 and 2015 during an intense rivalry with teammate Nico Rosberg. Following Rosberg's retirement in 2016, Ferrari's Sebastian Vettel became Hamilton's closest rival in two championship battles, in which Hamilton twice overturned mid-season point deficits to claim consecutive titles again in 2017 and 2018. His third and fourth consecutive titles followed in 2019 and 2020 to equal Schumacher's record of seven drivers' titles. Hamilton has been credited with furthering Formula One's global following by appealing to a broader audience outside the sport, in part due to his high-profile lifestyle, environmental and social activism, and exploits in music and fashion. He has also become a prominent advocate in support of activism to combat racism and push for increased diversity in motorsport. Hamilton was listed in the 2020 issue of Time as one of the 100 most influential people globally, and was knighted in the 2021 New Year Honours.")
                ],
                    carImage: "mercedesCar"),
            Team(name: "Aston Martin", imageName: "astonMartinLogo", drivers: [
                Driver(name: "Fernando Alonso",
                       summary: "Fernando Alonso Díaz was born 29 July 1981 is a Spanish racing driver currently competing for Aston Martin in Formula One. He won the series' World Drivers' Championship in 2005 and 2006 with Renault, and has also driven for McLaren, Ferrari, and Minardi. With Toyota, Alonso won the 24 Hours of Le Mans twice, in 2018 and 2019, and the FIA World Endurance Championship in 2018–19. He also won the 24 Hours of Daytona with Wayne Taylor Racing in 2019. As of 2022, Alonso is the only driver to win both the F1 World Drivers' Championship and the World Endurance Championship, even if the World Sportscar Championship is included in WEC.",
                       driverNumber: "14",
                       imageName: "fernandoAlonso",
                       longDescription: "Born in Oviedo, Asturias to a working-class family, Alonso began kart racing at the age of three and achieved success in local, national, and world championships. He progressed to car racing at the age of 17, winning the Euro Open by Nissan in 1999 and was fourth in the International Formula 3000 Championship of 2000. He debuted in Formula One with Minardi in 2001 before joining Renault as a test driver for 2002. Promoted to a race seat in 2003, Alonso won two drivers' championships in 2005 and 2006, becoming the youngest pole-sitter, youngest race winner, youngest world champion, and youngest two-time champion in the sport's history at the time. After finishing just one point behind eventual champion Kimi Räikkönen with McLaren in 2007, he returned to Renault for 2008 and 2009 and won two races in the former year for fifth overall. Alonso drove for Ferrari from 2010 to 2014, finishing runner-up to Sebastian Vettel in 2010, 2012, and 2013 with the title battles in 2010 and 2012 going down to the last race of the season. A second stint with McLaren from 2015 to 2018 resulted in no further success. After a two-year sabbatical, Alonso returned to Formula One in 2021 with Alpine. At the 2021 Qatar Grand Prix, Alonso scored his first podium in seven years. At the 2022 Singapore Grand Prix, he broke the record for most starts in Formula One. At the 2023 Saudi Arabian Grand Prix, Alonso scored his 100th podium by finishing third, becoming one of six drivers in the series' history to achieve that feat. At the time of his sabbatical, Alonso had won 32 Grands Prix, 22 pole positions, and 1,899 points from 311 starts. He is currently the only Spanish Formula One driver to have won the World Championship. Until Carlos Sainz's maiden win at the 2022 British Grand Prix, Alonso was the only Spaniard to win a Formula One Grand Prix. Alonso won the 2001 Race of Champions Nations Cup with the rally driver Jesús Puras and the motorcyclist Rubén Xaus for Team Spain and thrice entered the Indianapolis 500 in 2017, 2019 and 2020. He has been awarded the Prince of Asturias Award for Sports, the Premios Nacionales del Deporte Sportsman of the Year Award and the Gold Medal of the Royal Order of Sports Merit and has twice been inducted into the FIA Hall of Fame. Alonso runs an esports and junior racing team and is a UNICEF Goodwill Ambassador."),
                Driver(name: "Lance Stroll",
                       summary: "Lance Strulovitch was born 29 October 1998, better known as Lance Stroll, is a Canadian and Belgian racing driver competing under the Canadian flag in Formula One. He has driven for Aston Martin since 2021, having previously driven for Williams and Racing Point. He was Italian F4 champion in 2014, Toyota Racing Series champion in 2015, and 2016 FIA European Formula 3 champion. He was part of the Ferrari Driver Academy from 2010 to 2015. He achieved his first podium finish, a 3rd place, at the 2017 Azerbaijan Grand Prix, becoming the second-youngest driver to finish an F1 race on the podium and the youngest (and latest as of the end of 2022) to do so during his rookie season. At the 2020 Turkish Grand Prix, Stroll took his first pole position in Formula One. Stroll also competed in endurance racing, taking part in the 24 Hours of Daytona in 2016 and 2018.",
                       driverNumber: "18",
                       imageName: "lanceStroll",
                       longDescription: "Stroll is the son of Canadian billionaire businessman Lawrence Stroll (part-owner of the Aston Martin Formula One team) and Belgian fashion designer Claire-Anne Callens, and has an older sister named Chloe. His parents are divorced and his father has since remarried to Raquel Diniz. He is of Russian Jewish descent from his father's side. Stroll races under the Canadian flag and holds both Canadian and Belgian citizenship. He is multilingual speaking English, French, Flemish, and Italian. Stroll drove for the Williams team for the 2017 Formula One season, partnering Felipe Massa. He became the first Canadian Formula One driver since the 1997 World Drivers' Champion Jacques Villeneuve. Reportedly, Stroll's father Lawrence paid $80 million to Williams prior to his Formula One debut.")
            ],
                carImage: "astonMartinCar"),
            Team(name: "Ferrari", imageName: "ferrariLogo", drivers: [
                Driver(name: "Charles Leclerc",
                       summary: "Charles Marc Hervé Perceval Leclerc was born 16 October 1997, is a Monégasque racing driver, currently racing in Formula One for Scuderia Ferrari. He won the GP3 Series championship in 2016 and the FIA Formula 2 Championship in 2017.",
                       driverNumber: "16",
                       imageName: "charlesLeclerc",
                       longDescription: "Leclerc made his Formula One debut in 2018 for Sauber, a team affiliated with Ferrari, for which he was part of the Ferrari Driver Academy. With Sauber having finished last the year before, Leclerc led the charge to improve its finishing position in the Constructors' Championship to eighth, and was the higher ranked of the two Sauber drivers. He joined Ferrari the next season and became the second-youngest driver to qualify on pole position in Formula One at the 2019 Bahrain Grand Prix. The 2019 season also saw Leclerc take his first career win in Belgium. He won the FIA Pole Trophy for most pole positions in the 2019 season, becoming the youngest driver to win it, before winning it again in 2022. Leclerc finished runner-up to Max Verstappen in the 2022 World Drivers' Championship. As of the 2023 Belgian Grand Prix, Leclerc has achieved 5 race wins and 20 pole positions in Formula One. He scored the first grand slam of his career at the 2022 Australian Grand Prix. Leclerc is set to remain at Ferrari until at least the end of the 2024 season. Charles Leclerc’s brother, Arthur Leclerc, currently races in Formula 2. Charles is the godson of former F1 driver Jules Bianchi."),
                Driver(name: "Carlos Sainz",
                       summary: "Carlos Sainz Vázquez de Castro was born 1 September 1994, otherwise known as Carlos Sainz Jr. or simply Carlos Sainz, is a Spanish racing driver currently competing in Formula One for Scuderia Ferrari. He is the son of Carlos Sainz Sr., a double World Rally Champion.",
                       driverNumber: "55",
                       imageName: "carlosSainz",
                       longDescription: "In 2012, Sainz raced in the British and European Formula 3 championships for Carlin. He raced for DAMS in the 2014 Formula Renault 3.5 season, winning the championship before moving to F1 with Toro Rosso. Sainz moved to McLaren for the 2019 season, while at the same time ending his contract with Red Bull Racing. At the 2019 Brazilian Grand Prix Sainz took his maiden Formula One podium finish with third. Sainz moved to Ferrari at the end of the 2020 season. At the 2022 British Grand Prix, Sainz took his maiden Formula One pole position and career win.")
            ],
                carImage: "ferrariCar"),
            Team(name: "McLaren", imageName: "mclarenLogo", drivers: [
                Driver(name: "Lando Norris",
                       summary: "Lando Norris was born 13 November 1999 and is a British and Belgian racing driver currently competing in Formula One with McLaren, racing under the British flag. He won the MSA Formula championship in 2015, and the Toyota Racing Series, Eurocup Formula Renault 2.0 and Formula Renault 2.0 Northern European Cup in 2016.",
                       driverNumber: "4",
                       imageName: "landoNorris",
                       longDescription: "He also received the McLaren Autosport BRDC Award that year. He subsequently joined the McLaren Young Driver Programme in 2017 and won the 2017 FIA Formula 3 European Championship, competing with Carlin Motorsport. Consequently, he was promoted to the Formula 2 Carlin team, where he finished second in 2018. He was then announced as a McLaren driver in 2018, alongside Carlos Sainz Jr. He achieved his first podium in Formula One at the 2020 Austrian Grand Prix."),
                Driver(name: "Oscar Piastri",
                       summary: "Oscar Jack Piastri was born 6 April 2001 and is an Australian racing driver currently competing in Formula One for McLaren.",
                       driverNumber: "81",
                       imageName: "oscarPiastri",
                       longDescription: "He won the 2019 Formula Renault Eurocup with R-ace GP, and won the 2020 FIA Formula 3 Championship and 2021 Formula 2 Championship with Prema Racing. He is only the sixth driver to win the GP2/Formula 2 Championship in their rookie season, and the fifth driver to win the GP3/Formula 3 Championship and the GP2/Formula 2 Championship in consecutive seasons. Due to his success in lower formulae, Piastri is widely considered as one of the most promising young drivers in motorsport.")
            ],
                carImage: "mclarenCar"),
            Team(name: "Alpine", imageName: "alpineLogo", drivers: [
                Driver(name: "Pierre Gasly",
                       summary: "Pierre Jean-Jacques Gasly was born 7 February 1996 and is a French racing driver currently competing in Formula One for Alpine. He won the 2016 GP2 Series championship, and finished as runner-up in the 2014 Formula Renault 3.5 Series and the 2017 Super Formula Championship.",
                       driverNumber: "10",
                       imageName: "pierreGasly",
                       longDescription: "Gasly made his Formula One debut with Toro Rosso at the 2017 Malaysian Grand Prix. He moved to Red Bull Racing in 2019, before being demoted and replaced with Alexander Albon from Toro Rosso between the Hungarian and Belgian rounds. Regardless, Gasly achieved his first podium at the 2019 Brazilian Grand Prix, finishing second. He won at the 2020 Italian Grand Prix while driving for AlphaTauri, securing both his and the teams' maiden victory in Formula One. He would achieve another podium at the 2021 Azerbaijan Grand Prix by finishing third behind eventual race winner Sergio Pérez and Sebastian Vettel. Gasly moved to Alpine for the 2023 season. Gasly's first race for the team was the 2023 Bahrain Grand Prix, in which he finished ninth."),
                Driver(name: "Esteban Ocon",
                       summary: "Esteban José Jean-Pierre Ocon-Khelfane was born 17 September 1996 and is a French racing driver currently competing in Formula One for Alpine.",
                       driverNumber: "31",
                       imageName: "estebanOcon",
                       longDescription: "Ocon experienced a successful junior career as he won the 2014 FIA Formula 3 European Championship and the 2015 GP3 Series despite only winning one race in the latter campaign, which earned him a place at the Mercedes driver development programme, for whom he worked as a reserve driver. After winning the GP3 title, Ocon made his Formula One debut for Manor Racing in the 2016 Belgian Grand Prix, replacing Rio Haryanto. He moved to Force India/Racing Point in 2017, partnering Mexican driver Sergio Pérez for the 2017 and 2018 Formula 1 seasons. Ocon was sacked by Racing Point at the end of the 2018 season and thus became a reserve driver for Mercedes in 2019 until his move to Renault for 2020. He took his maiden Formula One podium at the 2020 Sakhir Grand Prix and maiden victory at the 2021 Hungarian Grand Prix. Despite not winning a race or taking a podium in 2022, he secured his best position in the drivers' standings in eighth with 92 points, 11 points clear of teammate Fernando Alonso, helping to secure fourth in the Constructors' Championship for Alpine.")
            ],
                carImage: "alpineCar"),
            Team(name: "Williams", imageName: "williamsLogo", drivers: [
                Driver(name: "Alexander Albon",
                       summary: "Alexander Albon Ansusinha was born 23 March 1996 and is a Thai and British racing driver currently competing in Formula One for Williams Racing, under the Thai flag. Albon previously raced in Formula One for Scuderia Toro Rosso and Red Bull Racing and in DTM for AF Corse.",
                       driverNumber: "23",
                       imageName: "alexanderAlbon",
                       longDescription: "After becoming part of the Red Bull Junior Team in 2012, he was promoted to open-wheel cars for the 2012 Eurocup Formula Renault 2.0 season. He spent three years in the series and finished third in the 2014 championship. He moved to the FIA Formula 3 European Championship in 2015, where he finished seventh. He signed with ART Grand Prix to contest the 2016 GP3 Series, and ended the season as runner-up behind teammate Charles Leclerc. In 2017 Albon moved up to the FIA Formula 2 Championship with ART, where he finished his maiden year tenth in the standings. He then switched to the DAMS team for 2018, winning four races and finishing third in the championship. He made his Formula One début in 2019 with Toro Rosso alongside Daniil Kvyat. After twelve races, Albon was promoted to Red Bull Racing, partnering Max Verstappen and replacing Pierre Gasly. He took his first podium finish – and the first in a World Championship Formula One race for a Thai driver – at the 2020 Tuscan Grand Prix. After two seasons in Formula One, Albon was demoted to a test and reserve driver role with Red Bull for 2021 and his seat was taken by Sergio Pérez. Albon returned to Formula One in 2022, driving for Williams, and continues with the team in 2023."),
                Driver(name: "Logan Sargeant",
                       summary: "Logan Hunter Sargeant was born December 31, 2000 and is an American racing driver who competes in Formula One for Williams Racing. He previously competed in the 2022 FIA Formula 2 Championship driving for Carlin Motorsport, finishing fourth overall in the standings.",
                       driverNumber: "2",
                       imageName: "loganSargeant",
                       longDescription: "In October 2021, on the weekend of the United States Grand Prix, Sargeant was announced to be joining the Williams Driver Academy. He got his first experience in an F1 car at the post-season test, driving the Williams FW43B on the Yas Marina Circuit. He described his first time in an F1 car as an \"experience of a lifetime.\" Sargeant made his Formula One practice debut with Williams at the 2022 United States Grand Prix. He was the first American driver to take part in a weekend session since Alexander Rossi in 2015. On his free practice debut, Jost Capito, Williams' team principal, stated that his debut \"was a pleasure and pressure for Sargeant\". Sargeant drove the Williams again at the Mexico City Grand Prix, the Sao Paulo Grand Prix and the Abu Dhabi Grand Prix.")
            ],
                carImage: "williamsCar"),
            Team(name: "Haas", imageName: "haasLogo", drivers: [
                Driver(name: "Kevin Magnussen",
                       summary: "Kevin Jan Magnussen was born 5 October 1992 and is a Danish racing driver currently competing in Formula One for Haas F1 Team.",
                       driverNumber: "20",
                       imageName: "kevinMagnussen",
                       longDescription: "He is the son of four-time Le Mans winner and former Formula One driver Jan Magnussen. Magnussen came up through McLaren Formula One team's Young Driver Programme and drove for McLaren in the 2014 Formula One World Championship, before a stint with Renault in 2016. Magnussen drove for Haas from 2017 until the end of the 2020 season. In 2022, Magnussen rejoined Haas on a multi-year deal."),
                Driver(name: "Nico Hulkenburg",
                       summary: "Nicolas Hülkenberg was born 19 August 1987 and is a German racing driver who drives for the Haas F1 Team in Formula One. He was the 2009 GP2 Series champion, and is a previous champion of both the Formula 3 Euro Series and A1 Grand Prix, as part of A1 Team Germany. He is one of six drivers since 2005 to win the GP2 Series/Formula 2 championship in his debut season, the others being Lewis Hamilton, Nico Rosberg, Charles Leclerc, George Russell, and Oscar Piastri. Outside of Formula One, he won the 24 Hours of Le Mans in 2015 on his first attempt and also contested two rounds of the 2015 FIA World Endurance Championship season for Porsche.",
                       driverNumber: "27",
                       imageName: "nicoHulkenberg",
                       longDescription: "Hülkenberg graduated to Formula One in 2010 with the Williams team. Despite claiming the first pole position for Williams in more than five years, he was not retained for 2011 and joined Force India as a test and reserve driver, being promoted to a race seat with the team for the 2012 season. In 2013 he drove for the Sauber team, but returned to Force India for the 2014 season. In October 2016, it was confirmed that he would switch to Renault for 2017. He was replaced by Esteban Ocon for the 2020 Formula One season and left without a seat, in turn joining Racing Point as a reserve driver. In 2020, he drove for Racing Point in three races, following positive COVID tests for both Lance Stroll and Sergio Perez. He then would drive again in place of Sebastian Vettel at Aston Martin at the first two races of the 2022 season, following Vettel's positive COVID test. He returned as a full-time driver for the 2023 season, driving for Haas F1 Team. Hülkenberg currently holds the record for the most Formula One career starts without a podium finish, a record he broke when he failed to finish in his 129th race (the 2017 Singapore Grand Prix) and in so doing passed Adrian Sutil's previous record of 128; the record currently stands at 193 Grands Prix. As of July 2023 he also holds the record for most career points without a single race win, the record was attributed to him after its previous holder, Carlos Sainz Jr. won the 2022 British Grand Prix.")
            ],
                carImage: "haasCar"),
            Team(name: "Alfa Romeo", imageName: "alfaRomeoLogo", drivers: [
                Driver(name: "Valterri Bottas",
                       summary: "Valtteri Viktor Bottas was born 28 August 1989 and is a Finnish racing driver currently competing in Formula One for Alfa Romeo, having previously driven for Mercedes from 2017 to 2021 and Williams from 2013 to 2016. Bottas has scored 10 race wins and 67 podiums. He contributed to five constructors championship wins for Mercedes, and has been drivers' championship runner-up twice, in 2019 and 2020.",
                       driverNumber: "77",
                       imageName: "valtteriBottas",
                       longDescription: "Bottas started his racing career in karting, later advancing to single-seater championships such as the Formula Renault UK Winter Series, Formula Renault Eurocup and the Formula Renault Northern European Cup, winning the latter two in 2008. In 2009, he moved up to the Formula 3 Euroseries, finishing third in the championship and also winning the Masters of Formula 3 event. In 2010, he was hired as a test driver for the Williams Formula One team, a position he would retain throughout 2011 and 2012, taking part in 15 Friday Free Practice sessions. In 2011, he also took part in the GP3 Series, winning the championship in the final race of the season. In 2013, he joined Williams as a full-time driver partnering Pastor Maldonado. He would remain at Williams until 2017, achieving a top championship position of fourth in 2014 and finishing on the podium nine times during his time with Williams. Following Nico Rosberg's decision to retire following the 2016 season, Bottas was signed by Mercedes as his replacement to partner Lewis Hamilton. During his time with Mercedes which would go on to last until 2022, Bottas finished in the top three of the championship four times and won 10 races in addition to 58 podiums. After five constructor championships won alongside Hamilton, he joined Alfa Romeo for the 2022 season."),
                Driver(name: "Zhou Guanyu",
                       summary: "Zhou Guanyu was born 30 May 1999 and is a Chinese racing driver who currently competes in Formula One for Alfa Romeo. He is the first, and so far, the only Chinese driver to compete in Formula One. He competed in the FIA Formula 2 Championship for UNI-Virtuosi Racing from 2019 to 2021, having finished 3rd in the 2021 campaign.",
                       driverNumber: "24",
                       imageName: "zhouGuanyu",
                       longDescription: "A former member of the Alpine Academy, he served as the test driver for the Renault F1 Team and the Alpine F1 Team in 2020 and 2021 respectively. Prior to that, he was a member of the Ferrari Driver Academy from 2014 to 2018, and served as the development driver for Formula E team DS Techeetah in 2018.")
            ],
                carImage: "alfaRomeoCar"),
            Team(name: "AlphaTauri", imageName: "alphaTauriLogo", drivers: [
                Driver(name: "Yuki Tsunoda",
                       summary: "Yuki Tsunoda was born 11 May 2000 and is a Japanese racing driver currently competing in Formula One for Scuderia AlphaTauri. Supported by Honda since 2016 through the Honda Formula Dream Project, he was the 2018 Japanese F4 champion and in 2019 also received backing from Red Bull. He finished third in the 2020 Formula 2 Championship and made his Formula One debut in 2021 for AlphaTauri.",
                       driverNumber: "22",
                       imageName: "yukiTsunoda",
                       longDescription: "Tsunoda was signed by the Red Bull Junior Team for 2019 following his F4 Japanese Championship title. His first experience driving a Formula One car came in a November 2020 test session at Imola Circuit, driving the Toro Rosso STR13. The following month, he drove for AlphaTauri in the end-of-season rookie test at Yas Marina Circuit. He completed further test sessions in the STR14 at Imola Circuit and Misano Circuit over the winter break."),
                Driver(name: "Daniel Ricciardo",
                       summary: "Daniel Joseph Ricciardo was born 1 July 1989 and is an Australian and Italian racing driver currently competing in Formula One for Scuderia AlphaTauri under the Australian flag. He has achieved 8 Grand Prix victories and 32 podiums in Formula One.",
                       driverNumber: "3",
                       imageName: "danielRicciardo",
                       longDescription: "Ricciardo made his debut at the 2011 British Grand Prix with the HRT team as part of a deal with Red Bull Racing, for whom he was test driving under its sister team Scuderia Toro Rosso. He joined Toro Rosso in 2012 full-time after the team changed its driver lineup and drove a Ferrari-powered car for them in 2012 and 2013. In 2014, Ricciardo was promoted to Red Bull as a replacement for the retiring Mark Webber alongside Sebastian Vettel. In his first season with Red Bull under Renault power, Ricciardo finished third in the championship with his first three Formula One wins, in Canada, Hungary, and Belgium. After two years without a victory, Ricciardo returned to the top of the podium at the 2016 Malaysian Grand Prix, eventually sealing third in the championship for the second time in three years at the 2016 Mexican Grand Prix. He won again for Red Bull at the Azerbaijan Grand Prix in 2017 and the Chinese and Monaco Grands Prix in 2018. After 2018, Ricciardo signed with Renault and raced for them in the 2019 and 2020 seasons. He joined McLaren for the 2021 and 2022 Formula One seasons. He obtained his first race win with McLaren at the 2021 Italian Grand Prix. After the 2021 season, Ricciardo was appointed a Member of the Order of Australia in the 2022 Australia Day Honours. He left McLaren at the end of 2022 and became the third driver for Red Bull for the 2023 Formula One World Championship. He replaced the outgoing Nyck de Vries at AlphaTauri after the tenth round of the season, on loan from Red Bull Racing.")
            ],
                carImage: "alphaTauriCar")
        ]
    }
}
